FROM haproxy
USER root
COPY /haproxy/haproxy-config /usr/local/etc/haproxy/haproxy.cfg
RUN apt update && apt install -y libcap2-bin
RUN setcap 'cap_net_bind_service=+ep' /usr/local/sbin/haproxy
USER haproxy
CMD /bin/bash -c "/usr/local/sbin/haproxy -f /usr/local/etc/haproxy/haproxy.cfg"
